version: '3'
services:
  homescreen:
    build:
      context: .
      dockerfile: Dockerfile
    image: homescreen
    container_name: homescreen
    restart: unless-stopped
    environment:
      - PORT=3033
      - NODE_ENV=production
    command: npm start
    volumes:
      - .:/usr/app
    ports:
      - 3033:3033
